<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=windows-1250">
  <title>[nadpis]</title>
	<link rel="stylesheet" type="text/css" href="css/styl.css" media="screen" />
  [require]

  </head>
<body>

[images]
<h1>[nadpis]</h1>
<div id="text">[text]</div>
[folders]
<div id="seznam">
<ul>
[item]
<li><a href="[dir]">[name]</a></li>
[/item]
</ul>
</div>
[/folders]
<div id="galerie">
[image]
<a href="[target]" title="[title]">[mini]</a>
[/image]
</div>
[/images]



[items]
<h1>Seznam galerií</h1>
<div id="seznam">
<ul>
[item]
<li><a href="[dir]">[name]</a></li>
[/item]
</ul>
</div>
[/items]
<div id="foo">[bottom]</div>
<div id="foo2"><a href="http://lynt.cz" title="sítě, servery, webové aplikace a marketing">&copy 2013 Lynt services</a> - sledujte nás na <a href="http://www.facebook.com/LyntServices">Facebooku</a></div>
</body>
</html>
